Updated the code of the first example of the Embedded windows section in the Windows chapter because it gave error[E0433]: failed to resolve: use of undeclared type Color